spring:
  application:
    name: delivery_project
weather:
  api:
    key: ${WEATHER_API_KEY}
jwt:
  issuer: delivery-insight
  # openssl rand -base64 64 | tr -d '\n'
  secret-key: ${JWT_SECRET}
  access-token-validity: 2h
  refresh-token-validity: 7d