otel.service.name=delivery-project
otel.resource.attributes=deployment.environment=local

otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=http://localhost:4318
otel.traces.sampler=always_on

otel.instrumentation.jdbc.enabled=true
otel.instrumentation.common.db-statement-sanitizer.enabled=true
